
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0
  

development:
  <<: *default
  database: joberani_development

 
test:
  <<: *default
  database: joberani_test


production:
  <<: *default
  database: joberani_production
  username: joberani
  password: <%= ENV['JOBERANI_DATABASE_PASSWORD'] %>
